# Generated by Django 5.1 on 2024-09-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='Capture.png', null=True, upload_to='images'),
        ),
    ]
