# Generated by Django 5.1 on 2024-09-17 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='user',
        ),
    ]
