# Generated by Django 5.1 on 2024-09-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_rename_friends_id_friendslist_friends_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='friendsList',
        ),
    ]
